name: Magento 2 Installation with DDEV

on:
  push:
    branches:
      - main

jobs:
  magento-install:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instalar Magento 2 con DDEV
      - name: Install Magento 2 with DDEV
        uses: julienloizelet/magento2-ddev-installation@v3
        with:
          php_version: "7.3"
          magento_version: "2.3.5"
          magento_repository: "https://repo.magento.com/"
          composer_auth: ${{ secrets.M2_COMPOSER_AUTH }}
