name: Magento 2 Installation with DDEV

on:
  push:
    branches:
      - main

jobs:
  magento-install:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Instalar una versión local de Composer 2.1.x
      - name: Install Composer v2.1.x locally
        run: |
          curl -sS https://getcomposer.org/installer | php -- --version=2.1.14
          mv composer.phar composer

      # Paso 3: Crear un proyecto de Magento 2.3.5
      - name: Create Magento project
        run: |
          ./composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.3.5 ./magento

      # Paso 4: Ajustar dependencias problemáticas
      - name: Adjust problematic dependencies
        working-directory: ./magento
        run: |
          ./composer require laminas/laminas-dependency-plugin:^1.0 --no-update
          ./composer require dealerdirect/phpcodesniffer-composer-installer:^0.5 --no-update
          ./composer update --ignore-platform-reqs --no-interaction

      # Paso 5: Configurar Magento con DDEV
      - name: Configure Magento in DDEV
        working-directory: ./magento
        run: |
          ddev start
          ddev exec bin/magento setup:install \
            --base-url=https://m2.ddev.site \
            --db-host=db \
            --db-name=db \
            --db-user=db \
            --db-password=db \
            --backend-frontname=admin \
            --admin-firstname=admin \
            --admin-lastname=admin \
            --admin-email=admin@example.com \
            --admin-user=admin \
            --admin-password=admin123 \
            --language=en_US \
            --currency=USD \
            --timezone=America/Chicago \
            --use-rewrites=1