name: Magento 2 Installation with DDEV

on:
  push:
    branches:
      - main

jobs:
  magento-install:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Instalar PHP 7.3
      - name: Set up PHP 7.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'

      # Paso 2: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 3: Instalar Composer 1.x
      - name: Install Composer 1.x locally
        run: |
          curl -sS https://getcomposer.org/installer | php -- --1
          mv composer.phar composer

      # Paso 4: Configurar autenticación para Composer
      - name: Configure Composer Authentication
        run: |
          echo '{
            "http-basic": {
              "repo.magento.com": {
                "username": "b893576f694008764f5e376c4f5da092",
                "password": "1f285634b091d0d9df0778750dd8d4d9"
              }
            }
          }' > ~/.composer/auth.json

      # Paso 5: Crear el proyecto de Magento con Composer 1.x
      - name: Create Magento project
        run: |
          ./composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.3.5 ./magento

      # Paso 6: Configurar dependencias manualmente
      - name: Adjust problematic dependencies
        working-directory: ./magento
        run: |
          ./composer require dealerdirect/phpcodesniffer-composer-installer:^0.5 --dev
          ./composer require laminas/laminas-dependency-plugin:^1.0 --dev

      # Paso 7: Configurar Magento con DDEV
      - name: Configure Magento in DDEV
        working-directory: ./magento
        run: |
          ddev start
          ddev exec bin/magento setup:install \
            --base-url=https://m2.ddev.site \
            --db-host=db \
            --db-name=db \
            --db-user=db \
            --db-password=db \
            --backend-frontname=admin \
            --admin-firstname=admin \
            --admin-lastname=admin \
            --admin-email=admin@example.com \
            --admin-user=admin \
            --admin-password=admin123 \
            --language=en_US \
            --currency=USD \
            --timezone=America/Chicago \
            --use-rewrites=1